// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUnLzBo6RZuMUul2fMx6e1LHD8i83H6Bk',
    appId: '1:1075540931631:web:b3f770ebe11df77aeb82da',
    messagingSenderId: '1075540931631',
    projectId: 'buttonweb-2e860',
    authDomain: 'buttonweb-2e860.firebaseapp.com',
    storageBucket: 'buttonweb-2e860.firebasestorage.app',
    measurementId: 'G-HFJTE52BC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALUguNVPQ1L8L2TZ98lORMtw29sBVklS4',
    appId: '1:1075540931631:android:26c8a031310ed061eb82da',
    messagingSenderId: '1075540931631',
    projectId: 'buttonweb-2e860',
    storageBucket: 'buttonweb-2e860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdusREU8jEFHB3EfS3IabX6gWrVlXRvA',
    appId: '1:1075540931631:ios:14b15cab5d74c908eb82da',
    messagingSenderId: '1075540931631',
    projectId: 'buttonweb-2e860',
    storageBucket: 'buttonweb-2e860.firebasestorage.app',
    iosBundleId: 'com.example.fcmpractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhdusREU8jEFHB3EfS3IabX6gWrVlXRvA',
    appId: '1:1075540931631:ios:14b15cab5d74c908eb82da',
    messagingSenderId: '1075540931631',
    projectId: 'buttonweb-2e860',
    storageBucket: 'buttonweb-2e860.firebasestorage.app',
    iosBundleId: 'com.example.fcmpractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUnLzBo6RZuMUul2fMx6e1LHD8i83H6Bk',
    appId: '1:1075540931631:web:b3f770ebe11df77aeb82da',
    messagingSenderId: '1075540931631',
    projectId: 'buttonweb-2e860',
    authDomain: 'buttonweb-2e860.firebaseapp.com',
    storageBucket: 'buttonweb-2e860.firebasestorage.app',
    measurementId: 'G-HFJTE52BC8',
  );

}